In [1]:
import torch


In [5]:

# 1차원 텐서들
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

# dim 인자 없이 텐서들을 연결
result = torch.cat([tensor1, tensor2])
print(result)

tensor([1, 2, 3, 4, 5, 6])


In [7]:
# 예시
state0 = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
state1 = torch.tensor([10, 11, 12, 13, 14, 15, 16, 17, 18])
state2 = torch.tensor([19, 20, 21, 22, 23, 24, 25, 26, 27])

state_batch = torch.cat([state0, state1, state2], dim=0)
print(state_batch)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27])


# Mask

In [9]:
a = torch.tensor([1,2,3,4,5])
mask = torch.tensor([True, True, False, False, True])

mask_val = torch.tensor([100,200,500])

a[mask] = mask_val

print(a)

tensor([100, 200,   3,   4, 500])


In [10]:
torch.tensor([[1,2,3,4]])

tensor([[1, 2, 3, 4]])

In [13]:
import torch.nn as nn
class DQN(nn.Module):##v5.1
    def __init__(self, state_size, action_size):
        super(DQN, self).__init__()
        self.fc1 = nn.Linear(state_size, 64)
        self.fc2 = nn.Linear(64, 64)
        self.fc3 = nn.Linear(64, 64)
        self.relu = nn.ReLU()
        self.fc4 = nn.Linear(64, action_size)

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.relu(self.fc3(x))
        return self.fc4(x)

In [18]:
dqn = DQN(3,4)

In [23]:
dqn(torch.tensor([[1,2,3],[1,2,3],[4,5,6]], dtype=torch.float))

tensor([[ 0.1989,  0.0366, -0.0228, -0.1228],
        [ 0.1989,  0.0366, -0.0228, -0.1228],
        [ 0.1975,  0.1238,  0.0761, -0.1463]], grad_fn=<AddmmBackward0>)

In [24]:
class TestClass:
    def test_func(self):
        if self.aaa is None:
            print("None")
        else:
            self.aaa = "abc123"
            print(self.aaa)
t = TestClass()

t.test_func()
t.test_func()

AttributeError: 'TestClass' object has no attribute 'aaa'