In [1]:
import torch


In [5]:

# 1차원 텐서들
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

# dim 인자 없이 텐서들을 연결
result = torch.cat([tensor1, tensor2])
print(result)

tensor([1, 2, 3, 4, 5, 6])


In [7]:
# 예시
state0 = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
state1 = torch.tensor([10, 11, 12, 13, 14, 15, 16, 17, 18])
state2 = torch.tensor([19, 20, 21, 22, 23, 24, 25, 26, 27])

state_batch = torch.cat([state0, state1, state2], dim=0)
print(state_batch)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27])


# Mask

In [9]:
a = torch.tensor([1,2,3,4,5])
mask = torch.tensor([True, True, False, False, True])

mask_val = torch.tensor([100,200,500])

a[mask] = mask_val

print(a)

tensor([100, 200,   3,   4, 500])
